### ISSUE TITLE
grabteeth.xyz down – RPC failing

### ISSUE THREAD

**Issue by BuggerBag** [a16z/eth-testnet-drop#18]
hi, grabteeth.xyz is not working. background is very heavy.
can you post us 10 Eth for free.
our wallet address is: 0x7E1d0d71A604fa3840970D6E8EA3258F1c1E6388
i wonder if you'd mind the donation. thanks.

**Comment by sragss** [comment]
Currently the ankr public Goerli RPC is down. We're working to resolve.

**Comment by sragss** [comment]
Should be fixed, please try again.
